version: "3.5"
services:
  ############################################################################
  #                           POSTGRES - Database                            #
  ############################################################################
  postgres:
    image: postgres:13.6
    user: $USER_ID:$GROUP_ID
    command:
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      TZ: Asia/Tokyo
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    # Swarm
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=false
      resources:
        reservations:
          cpus: "0.1"
          memory: 1024M
    networks:
      - default
      - monitor

  ############################################################################
  #                    GRAPHNODES - indexering and query                     #
  ############################################################################

  index-node-0:
    image: graphprotocol/graph-node:${GRAPH_NODE_VERSION:-v0.28.2}
    environment:
      BLOCK_INGESTOR: index_node__0
      GRAPH_NODE_CONFIG: /var/config/config.toml
      ipfs: "${IPFS_ENDPOINT:-https://ipfs.network.thegraph.com}"
      GRAPH_KILL_IF_UNRESPONSIVE: "true"
      RUST_LOG: INFO
      GRAPH_LOG: INFO
      GRAPH_NODE_ID: "index_node__0"
      NODE_ID: "index_node__0"
      node_role: "index-node"
      STORE_CONNECTION_POOL_SIZE: ${STORE_CONNECTION_POOL_SIZE:-10}
      ETHEREUM_TRACE_STREAM_STEP_SIZE: ${ETHEREUM_TRACE_STREAM_STEP_SIZE:-50}
      ETHEREUM_BLOCK_BATCH_SIZE: ${ETHEREUM_BLOCK_BATCH_SIZE:-100}
      ETHEREUM_RPC_MAX_PARALLEL_REQUESTS: ${ETHEREUM_RPC_MAX_PARALLEL_REQUESTS:-64}
      GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: ${GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE:-500}
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: ${GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE:-200}
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: "true"
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    configs:
      - source: ${CHAIN_CONF_NAME}
        target: /var/config/config.toml
    # Swarm
    networks:
      - default
      - monitor
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  index-node-1:
    image: graphprotocol/graph-node:${GRAPH_NODE_VERSION:-v0.28.2}
    environment:
      DISABLE_BLOCK_INGESTOR: 'true'
      GRAPH_NODE_CONFIG: /var/config/config.toml
      ipfs: "${IPFS_ENDPOINT:-https://ipfs.network.thegraph.com}"
      GRAPH_KILL_IF_UNRESPONSIVE: "true"
      RUST_LOG: INFO
      GRAPH_LOG: INFO
      GRAPH_NODE_ID: "index_node__1"
      NODE_ID: "index_node__1"
      node_role: "index-node"
      STORE_CONNECTION_POOL_SIZE: ${STORE_CONNECTION_POOL_SIZE:-10}
      ETHEREUM_TRACE_STREAM_STEP_SIZE: ${ETHEREUM_TRACE_STREAM_STEP_SIZE:-50}
      ETHEREUM_BLOCK_BATCH_SIZE: ${ETHEREUM_BLOCK_BATCH_SIZE:-100}
      ETHEREUM_RPC_MAX_PARALLEL_REQUESTS: ${ETHEREUM_RPC_MAX_PARALLEL_REQUESTS:-64}
      GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: ${GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE:-500}
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: ${GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE:-200}
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: "true"
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    configs:
      - source: ${CHAIN_CONF_NAME}
        target: /var/config/config.toml
    # Swarm
    networks:
      - default
      - monitor
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  query-node:
    image: graphprotocol/graph-node:${GRAPH_NODE_VERSION:-v0.28.2}
    environment:
      DISABLE_BLOCK_INGESTOR: 'true'
      GRAPH_NODE_CONFIG: /var/config/config.toml
      ipfs: "${IPFS_ENDPOINT:-https://ipfs.network.thegraph.com}"
      RUST_LOG: INFO
      GRAPH_LOG: INFO
      GRAPH_NODE_ID: "query_node"
      NODE_ID: "query_node"
      node_role: "query-node"
      GRAPH_ETH_CALL_GAS: 50000000
      GRAPH_GETH_ETH_CALL_ERRORS: "out of gas"
      GRAPH_MAX_GAS_PER_HANDLER: 1000000000000000
      EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: synced
      GRAPH_KILL_IF_UNRESPONSIVE: "true"
      DISABLE_BLOCK_INGESTOR: "true"
      GRAPH_LOG_QUERY_TIMING: ${GRAPH_LOG_QUERY_TIMING:-gql}
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: ${FULLTEXT_SEARCH:-true}
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    configs:
      - source: ${CHAIN_CONF_NAME}
        target: /var/config/config.toml
    networks:
      - default
      - monitor
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager

networks:
  default:
    name: indexer_default
  monitor:
    external: true
configs:
  ${CHAIN_CONF_NAME}:
    external: true
