version: "3.5"
services:
  ############################################################################
  #               indexer-console - WebUI for indexer-cli                    #
  ############################################################################
  console:
    image: wrfly/container-web-tty:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.indexer-console-http.rule: Host(`${CONSOLE_DOMAIN}`)
        traefik.http.middlewares.console-auth.basicauth.users: ${CONSOLE_USER}:${CONSOLE_HASHED_PASSWORD}
        traefik.http.routers.indexer-console-https.entrypoints: https
        traefik.http.routers.indexer-console-http.entrypoints: http
        traefik.constraint-label: traefik-public
        traefik.http.routers.indexer-console-https.tls.certresolver: le
        traefik.http.routers.indexer-console-http.middlewares: https-redirect
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.http.routers.indexer-console-https.middlewares: console-auth
        traefik.http.services.indexer-console.loadbalancer.server.port: "8080"
        traefik.http.routers.indexer-console-https.tls: "true"
        traefik.http.routers.indexer-console-https.rule: Host(`${CONSOLE_DOMAIN}`)
      placement:
        constraints:
          - node.role == manager
  indexer-cli:
    image: ghcr.io/graphprotocol/indexer-cli:v0.18.6
    tty: true
    networks:
      - default
      - monitor
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  default:
    driver: overlay
  traefik-public:
    external: true
  monitor:
    external: true
