version: "3.5"
services:
  ############################################################################
  #          POSTGRES - Database for index-agent/index-service               #
  ############################################################################
  postgres-indexer:
    image: postgres:13.6
    user: $USER_ID:$GROUP_ID
    command:
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: indexer
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      TZ: Asia/Tokyo
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    # Swarm
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == indexer-manager
      labels:
        - traefik.enable=false
    networks:
      - default
      - monitor

  ############################################################################
  #                         Indexer Agent/Service                            #
  ############################################################################

  indexer-agent:
    image: ghcr.io/graphprotocol/indexer-agent:${INDEXER_VERSION:-v0.20.5-alpha.1}
    environment:
      INDEXER_AGENT_ETHEREUM: ${INDEXER_RPC}
      INDEXER_AGENT_ETHEREUM_NETWORK: goerli
      INDEXER_AGENT_INDEXER_ADDRESS: ${INDEXER_ADDRESS}
      INDEXER_AGENT_MNEMONIC: ${INDEXER_MNEMONIC}
      INDEXER_AGENT_GEO_COORDINATES: ${INDEXER_GEO}
      INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT: https://gateway.testnet.thegraph.com/network
      INDEXER_AGENT_COLLECT_RECEIPTS_ENDPOINT: https://gateway.testnet.thegraph.com/collect-receipts
      INDEXER_AGENT_EPOCH_SUBGRAPH_ENDPOINT: https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle
      # CHECK THIS. we should choose this...
      INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT: ${INDEXER_QUERY_ENDPOINT:-http://indexer-gnosis_query-node:8000}
      INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT: ${INDEXER_ADMIN_ENDPOINT:-http://indexer-gnosis_index-node:8020}
      INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT: ${INDEXER_NODE_STATUS_ENDPOINT:-http://indexer-gnosis_index-node:8030/graphql}
      INDEXER_AGENT_PUBLIC_INDEXER_URL: https://${INDEXER_DOMAIN}
      INDEXER_AGENT_INDEX_NODE_IDS: index_node_gnosis
      INDEXER_AGENT_INDEXER_MANAGEMENT_PORT: 8000
      INDEXER_AGENT_POSTGRES_HOST: "postgres-indexer"
      INDEXER_AGENT_POSTGRES_DATABASE: "indexer"
      INDEXER_AGENT_POSTGRES_USERNAME: "${DB_USER}"
      INDEXER_AGENT_POSTGRES_PASSWORD: "${DB_PASSWORD}"
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - default
      - monitor
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == indexer-manager

  indexer-service:
    image: ghcr.io/graphprotocol/indexer-service:${INDEXER_VERSION:-v0.20.5-alpha.1}
    environment:
      INDEXER_SERVICE_ETHEREUM: ${INDEXER_RPC}
      INDEXER_SERVICE_ETHEREUM_NETWORK: goerli
      INDEXER_SERVICE_INDEXER_ADDRESS: ${INDEXER_ADDRESS}
      INDEXER_SERVICE_MNEMONIC: ${INDEXER_MNEMONIC}
      INDEXER_SERVICE_NETWORK_SUBGRAPH_DEPLOYMENT: ${INDEXER_NETWORK_SUBGRAPH:-QmeTrzKtD7fuNScLZFE4QtcmFqNfcePRumkHNdZhoZSA3G}
      INDEXER_SERVICE_NETWORK_SUBGRAPH_ENDPOINT: https://gateway.testnet.thegraph.com/network
      INDEXER_SERVICE_CLIENT_SIGNER_ADDRESS: "0xe1EC4339019eC9628438F8755f847e3023e4ff9c"
      INDEXER_SERVICE_GRAPH_NODE_QUERY_ENDPOINT: ${INDEXER_QUERY_ENDPOINT:-http://indexer-gnosis_query-node:8000}
      INDEXER_SERVICE_GRAPH_NODE_ADMIN_ENDPOINT: ${INDEXER_ADMIN_ENDPOINT:-http://indexer-gnosis_index-node:8020}
      INDEXER_SERVICE_GRAPH_NODE_STATUS_ENDPOINT: ${INDEXER_NODE_STATUS_ENDPOINT:-http://indexer-gnosis_index-node:8030/graphql}
      INDEXER_SERVICE_SERVER_PORT: 5432
      INDEXER_SERVICE_POSTGRES_HOST: "postgres-indexer"
      INDEXER_SERVICE_POSTGRES_DATABASE: "indexer"
      INDEXER_SERVICE_POSTGRES_USERNAME: "${DB_USER}"
      INDEXER_SERVICE_POSTGRES_PASSWORD: "${DB_PASSWORD}"
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # Swarm
    networks:
      - default
      - traefik-public
      - monitor
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == indexer-manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.indexer-service-http.rule=Host(`${INDEXER_DOMAIN}`)"
        - traefik.http.routers.indexer-service-http.entrypoints=http
        - traefik.http.routers.indexer-service-http.middlewares=https-redirect
        - "traefik.http.routers.indexer-service-https.rule=Host(`${INDEXER_DOMAIN}`)"
        - traefik.http.routers.indexer-service-https.entrypoints=https
        - traefik.http.routers.indexer-service-https.tls=true
        - traefik.http.routers.indexer-service-https.tls.certresolver=le
        - traefik.http.services.indexer-service.loadbalancer.server.port=7600

  ############################################################################
  #                      node-exporter - Export data                         #
  ############################################################################

  node-exporter:
    image: prom/node-exporter
    # Swarm
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == indexer-manager
      labels:
        - traefik.enable=false
    networks:
      - default
      - monitor

  ############################################################################
  #                      postgres-exporter - Export data                     #
  ############################################################################

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == indexer-manager
      labels:
        - traefik.enable=false
    networks:
      - default
      - monitor

  ############################################################################
  #               indexer-console - WebUI for indexer-cli                    #
  ############################################################################
  console:
    image: wrfly/container-web-tty:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.indexer-console-http.rule: Host(`${CONSOLE_DOMAIN}`)
        traefik.http.middlewares.console-auth.basicauth.users: ${CONSOLE_USER}:${CONSOLE_HASHED_PASSWORD}
        traefik.http.routers.indexer-console-https.entrypoints: https
        traefik.http.routers.indexer-console-http.entrypoints: http
        traefik.constraint-label: traefik-public
        traefik.http.routers.indexer-console-https.tls.certresolver: le
        traefik.http.routers.indexer-console-http.middlewares: https-redirect
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.http.routers.indexer-console-https.middlewares: console-auth
        traefik.http.services.indexer-console.loadbalancer.server.port: "8080"
        traefik.http.routers.indexer-console-https.tls: "true"
        traefik.http.routers.indexer-console-https.rule: Host(`${CONSOLE_DOMAIN}`)
      placement:
        constraints:
          - node.role == manager
  indexer-cli:
    image: ghcr.io/graphprotocol/indexer-cli:sha-4c31f45
    tty: true
    networks:
      - default
      - monitor
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  default:
    name: indexer_default
  monitor:
    external: true
  traefik-public:
    external: true
configs:
  ${CHAIN_CONF_NAME}:
    external: true
