version: "3.5"
services:
  ############################################################################
  #                         Indexer Agent/Service                            #
  ############################################################################

  indexer-agent:
    image: ghcr.io/graphprotocol/indexer-agent:${INDEXER_VERSION:-v0.18.6}
    environment:
      INDEXER_AGENT_ETHEREUM: ${INDEXER_RPC}
      INDEXER_AGENT_ETHEREUM_NETWORK: mainnet
      INDEXER_AGENT_INDEXER_ADDRESS: ${INDEXER_ADDRESS}
      INDEXER_AGENT_MNEMONIC: ${INDEXER_MNEMONIC}
      INDEXER_AGENT_GEO_COORDINATES: ${INDEXER_GEO}
      INDEXER_AGENT_PUBLIC_INDEXER_URL: https://indexer.${ROOT_DOMAIN}
      INDEXER_AGENT_NETWORK_SUBGRAPH_DEPLOYMENT: ${INDEXER_NETWORK_SUBGRAPH:-QmV614UpBCpuusv5MsismmPYu4KqLtdeNMKpiNrX56kw6u}
      INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT: https://gateway.thegraph.com/network
      INDEXER_AGENT_COLLECT_RECEIPTS_ENDPOINT: https://gateway.thegraph.com/collect-receipts
      INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT: ${INDEXER_QUERY_ENDPOINT:-http://query-node:8000}
      INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT: ${INDEXER_ADMIN_ENDPOINT:-http://index-node-0:8020}
      INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT: ${INDEXER_NODE_STATUS_ENDPOINT:-http://index-node-0:8030/graphql}
      INDEXER_AGENT_DAI_CONTRACT: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
      INDEXER_AGENT_GAS_PRICE_MAX: 40
      INDEXER_AGENT_REBATE_CLAIM_THRESHOLD: 200
      INDEXER_AGENT_REBATE_CLAIM_BATCH_THRESHOLD: 2000
      INDEXER_AGENT_VOUCHER_EXPIRATION: 2160
      INDEXER_AGENT_INDEX_NODE_IDS: index_node_0, index_node_1
      INDEXER_AGENT_INDEXER_MANAGEMENT_PORT: 8000
      INDEXER_AGENT_POSTGRES_HOST: "postgres"
      INDEXER_AGENT_POSTGRES_DATABASE: "indexer"
      INDEXER_AGENT_POSTGRES_USERNAME: "${DB_USER}"
      INDEXER_AGENT_POSTGRES_PASSWORD: "${DB_PASSWORD}"
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - default
      - monitor
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  indexer-service:
    image: ghcr.io/graphprotocol/indexer-service:${INDEXER_VERSION:-v0.18.6}
    environment:
      INDEXER_SERVICE_ETHEREUM: ${INDEXER_RPC}
      INDEXER_SERVICE_ETHEREUM_NETWORK: mainnet
      INDEXER_SERVICE_INDEXER_ADDRESS: ${INDEXER_ADDRESS}
      INDEXER_SERVICE_MNEMONIC: ${INDEXER_MNEMONIC}
      INDEXER_SERVICE_NETWORK_SUBGRAPH_DEPLOYMENT: ${INDEXER_NETWORK_SUBGRAPH:-QmV614UpBCpuusv5MsismmPYu4KqLtdeNMKpiNrX56kw6u}
      INDEXER_SERVICE_NETWORK_SUBGRAPH_ENDPOINT: https://gateway.thegraph.com/network
      INDEXER_SERVICE_CLIENT_SIGNER_ADDRESS: "0x982D10c56b8BBbD6e09048F5c5f01b43C65D5aE0"
      INDEXER_SERVICE_GRAPH_NODE_QUERY_ENDPOINT: ${INDEXER_QUERY_ENDPOINT:-http://query-node:8000}
      INDEXER_SERVICE_GRAPH_NODE_ADMIN_ENDPOINT: ${INDEXER_ADMIN_ENDPOINT:-http://index-node-0:8020}
      INDEXER_SERVICE_GRAPH_NODE_STATUS_ENDPOINT: ${INDEXER_NODE_STATUS_ENDPOINT:-http://index-node-0:8030/graphql}
      INDEXER_SERVICE_SERVER_PORT: 5432
      INDEXER_SERVICE_POSTGRES_HOST: "postgres"
      INDEXER_SERVICE_POSTGRES_DATABASE: "indexer"
      INDEXER_SERVICE_POSTGRES_USERNAME: "${DB_USER}"
      INDEXER_SERVICE_POSTGRES_PASSWORD: "${DB_PASSWORD}"
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # Swarm
    networks:
      - default
      - traefik-public
      - monitor
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.indexer-service-http.rule=Host(`indexer.${ROOT_DOMAIN}`)"
        - traefik.http.routers.indexer-service-http.entrypoints=http
        - traefik.http.routers.indexer-service-http.middlewares=https-redirect
        - "traefik.http.routers.indexer-service-https.rule=Host(`indexer.${ROOT_DOMAIN}`)"
        - traefik.http.routers.indexer-service-https.entrypoints=https
        - traefik.http.routers.indexer-service-https.tls=true
        - traefik.http.routers.indexer-service-https.tls.certresolver=le
        - traefik.http.services.indexer-service.loadbalancer.server.port=7600

  ############################################################################
  #                         Indexer Console                            #
  ############################################################################

  indexer-cli:
    image: ghcr.io/graphprotocol/indexer-cli:v0.18.6
    user: $USER_ID:$GROUP_ID
    tty: true
    networks:
      - default
    volumes:
      - ../deployment/default.agora:/home/graph/default.agora:ro
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  default:
    name: indexer_default
  monitor:
    external: true
  traefik-public:
    external: true
