version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:2.16.2
    command:
      - -H
      - tcp://tasks.agent:9001
      - --tlsskipverify
    networks:
      - agent-network
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.portainer.middlewares=authelia@docker
        - traefik.https.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)
        - traefik.http.routers.portainer.entrypoints=https
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.tls.certresolver=le
        - traefik.http.services.portainer.loadbalancer.server.port=9000

  agent:
    image: portainer/agent:2.16.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    logging:
      driver: json-file
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  agent-network:
    driver: overlay
  traefik-public:
    external: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
