version: "3.3"

services:
  app:
    image: swarmpit/swarmpit:1.9
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.swarmpit.rule=Host(`swarmpit.${ROOT_DOMAIN}`)
        - traefik.http.routers.swarmpit.entrypoints=https
        - traefik.http.routers.swarmpit.tls=true
        - traefik.http.routers.swarmpit.tls.certresolver=le
        - traefik.http.services.swarmpit.loadbalancer.server.port=8080

  db:
    image: couchdb:2.3.0
    volumes:
      - ../data/swarmpit/db-data:/opt/couchdb/data
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 512M
        reservations:
          cpus: "0.15"
          memory: 256M
      placement:
        constraints:
          - node.labels.swarmpit.db-data == true
          - node.role == manager
  influxdb:
    image: influxdb:1.7
    volumes:
      - ../data/swarmpit/influx-data:/opt/couchdb/data
    networks:
      - default
    deploy:
      resources:
        reservations:
          cpus: "0.3"
          memory: 128M
        limits:
          cpus: "0.6"
          memory: 512M
      placement:
        constraints:
          - node.labels.swarmpit.influx-data == true
          - node.role == manager
  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.10"
          memory: 64M
        reservations:
          cpus: "0.05"
          memory: 32M
      placement:
        constraints:
          - node.role == manager

networks:
  default:
  traefik-public:
    external: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
