version: "3.5"
services:
  ############################################################################
  #                                MONITORING                                #
  ############################################################################

  prometheus:
    image: prom/prometheus
    user: $USER_ID:$GROUP_ID
    command:
      - "--log.level=warn"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ../data/prometheus:/prometheus
      - ../prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
    # Swarm
    networks:
      - default
      - monitor
      - traefik-public
    configs:
      - source: ${PROMETHEUS_CONF_NAME}
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
      # Traefik
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.monitor-prometheus-http.rule=Host(`${PROMETHEUS_DOMAIN}`)"
        - traefik.http.routers.monitor-prometheus-http.entrypoints=http
        - traefik.http.routers.monitor-prometheus-http.middlewares=https-redirect
        - "traefik.http.routers.monitor-prometheus-https.rule=Host(`${PROMETHEUS_DOMAIN}`)"
        - traefik.http.routers.monitor-prometheus-https.entrypoints=https
        - traefik.http.routers.monitor-prometheus-https.tls=true
        - traefik.http.routers.monitor-prometheus-https.tls.certresolver=le
        - traefik.http.services.monitor-prometheus.loadbalancer.server.port=9090
        - traefik.http.routers.monitor-prometheus-https.middlewares=prometheus-auth
        - traefik.http.middlewares.prometheus-auth.basicauth.users=${PROMETHEUS_USER}:${PROMETHEUS_HASHED_PASSWORD}

  grafana:
    image: grafana/grafana
    user: $USER_ID:$GROUP_ID
    environment:
      postgres_host: "postgres:5432"
      postgres_db: "${DB_NAME}"
      postgres_user: "${DB_USER}"
      postgres_pass: "${DB_PASSWORD}"
    volumes:
      - ../grafana:/etc/grafana/
      - ../data/grafana:/var/lib/grafana
    # Swarm
    networks:
      - default
      - monitor
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.monitor-grafana-http.rule=Host(`${GRAFANA_DOMAIN}`)"
        - traefik.http.routers.monitor-grafana-http.entrypoints=http
        - traefik.http.routers.monitor-grafana-http.middlewares=https-redirect
        - "traefik.http.routers.monitor-grafana-https.rule=Host(`${GRAFANA_DOMAIN}`)"
        - traefik.http.routers.monitor-grafana-https.entrypoints=https
        - traefik.http.routers.monitor-grafana-https.tls=true
        - traefik.http.routers.monitor-grafana-https.tls.certresolver=le
        - traefik.http.services.monitor-grafana.loadbalancer.server.port=3000

  alertmanager:
    image: prom/alertmanager
    user: $USER_ID:$GROUP_ID
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    volumes:
      - ../alertmanager:/etc/alertmanager
    networks:
      - default
      - monitor
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.monitor-alertmanager-http.rule=Host(`${ALERTMANAGER_DOMAIN}`)"
        - traefik.http.routers.monitor-alertmanager-http.entrypoints=http
        - traefik.http.routers.monitor-alertmanager-http.middlewares=https-redirect
        - "traefik.http.routers.monitor-alertmanager-https.rule=Host(`${ALERTMANAGER_DOMAIN}`)"
        - traefik.http.routers.monitor-alertmanager-https.entrypoints=https
        - traefik.http.routers.monitor-alertmanager-https.tls=true
        - traefik.http.routers.monitor-alertmanager-https.tls.certresolver=le
        - traefik.http.services.monitor-alertmanager.loadbalancer.server.port=9093

networks:
  default:
    name: monitor_default
  monitor:
    external: true
  traefik-public:
    external: true
configs:
  ${PROMETHEUS_CONF_NAME}:
    external: true
