groups:
  - name: targets
    rules:
      - alert: monitor_service_down
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Monitor service non-operational"
          description: "Service {{ $labels.instance }} is down."

  - name: containers
    rules:
      - alert: querynode_down
        expr: absent((time() - container_last_seen{container_label_com_docker_swarm_service_name="indexer-gnosis_index-node"}) < 30)
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Query Node down"
          description: "Query Node container is down for more than 30 seconds."

      - alert: indexnode_down
        expr: absent((time() - container_last_seen{container_label_com_docker_swarm_service_name="indexer-gnosis_query-node"}) < 30)
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Index Node down"
          description: "Index Node container is down for more than 30 seconds."

      - alert: postgres_down
        expr: absent((time() - container_last_seen{container_label_com_docker_swarm_service_name="indexer-gnosis_postgres"}) < 30)
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Postgres down"
          description: "Postgres container is down for more than 30 seconds."
