global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

alerting:

scrape_configs:
  - job_name: "graph-node"
    static_configs:
      - targets: ["index-node-0:8040", "index-node-1:8040", "query-node:8040"]
  - job_name: "indexer"
    static_configs:
      - targets: ["indexer-agent:7300", "indexer-service:7300"]
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "authelia"
    static_configs:
      - targets: ["authelia:9959"]
