global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

alerting:

scrape_configs:
  - job_name: "graph-node-ethereum"
    static_configs:
      - targets:
          [
            "indexer-ethereum_index-node-0:8040",
            "indexer-ethereum_index-node-1:8040",
            "indexer-ethereum_index-node:8040",
          ]
  - job_name: "indexer"
    static_configs:
      - targets: ["indexer_indexer-agent:7300", "indexer_indexer-service:7300"]
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
