global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "graph-node-gnosis"
    static_configs:
      - targets:
          ["indexer-gnosis_index-node:8040", "indexer-gnosis_query-node:8040"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
