{
 "title": "Custom Indexing Panels",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Eth RPC Request Duration per Subgraph",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deployment_eth_rpc_request_duration"
    }
   ]
  },
  {
   "title": "Eth RPC Errors per minute (all subgraphs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(eth_rpc_errors[1m]))"
    }
   ]
  },
  {
   "title": "Blocks behind over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "deployment_blocks_behind" }
   ]
  },
  {
   "title": "Blocks behind over time (all subgraphs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(deployment_blocks_behind)" }
   ]
  },
  {
   "title": "Blocks Processed per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(deployment_block_processing_duration_sum[1m])"
    }
   ]
  },
  {
   "title": "Blocks Processed per Minute (all subgraphs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_block_processing_duration_sum[1m]))"
    }
   ]
  }
 ]
}