{
 "title": "Graph Service Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "indexer",
     "queryText": "{\n  indexer(id: \"0x39839abed87475422c5353256d17e08395c3af6b\", orderBy: rewardsEarned, orderDirection: desc) {\n    id\n    account{\n      names {\n        name\n      }\n    }\n    rewardsEarned\n    queryFeesCollected\n    queryFeeRebates\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Indexer errors (over 5 minutes, by code)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_error[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Mean Queries per Second for the period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_ok[1m]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(indexer_service_queries_failed[1m]))",
     "legendFormat": "FAIL"
    }
   ]
  },
  {
   "title": "GRT PRICE /DAI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1/cost_model_automation_grt_per_dai",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_queries_ok[1m]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Total queries by subgraph per second [stacked]",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (rate(indexer_service_queries_total[1m]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_queries_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_queries_ok)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Channel Messages Failed vs OK per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_channel_messages_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_channel_messages_ok[1m]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Total Channel Messages by Servicenode per second [stacked]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(indexer_service_channel_messages_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Channel Messages Failed vs OK over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_channel_messages_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_channel_messages_ok)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Cost Model Queries per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_cost_model_queries_invalid[1m]))",
     "legendFormat": "queries_invalid"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries[1m]))",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries_failed[1m]))",
     "legendFormat": "batch queries_failed"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries_invalid[1m]))",
     "legendFormat": "batch  queries_invalid"
    }
   ]
  },
  {
   "title": "Total Cost Model Batch Queries by Servicenode per second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(indexer_service_cost_model_batch_queries[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cost Model Queries over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_cost_model_queries_invalid)",
     "legendFormat": "queries_invalid"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries)",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries_failed)",
     "legendFormat": "batch queries_failed"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries_invalid)",
     "legendFormat": "batch  queries_invalid"
    }
   ]
  }
 ]
}