{
 "title": "Service Status Board",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Service Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Index Node 1 Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"graph-index-node-1:8040\"}"
    }
   ]
  },
  {
   "title": "Index Node 2 Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"graph-index-node-2:8040\"}"
    }
   ]
  },
  {
   "title": "Query Node 1 Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"graph-query-node-1:8040\"}"
    }
   ]
  },
  {
   "title": "Indexer Agent Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"indexer-agent:7300\"}"
    }
   ]
  },
  {
   "title": "Indexer Service Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"indexer-service:7300\"}"
    }
   ]
  },
  {
   "title": "Ethereum Block Sync status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ethereum_chain_head_number" }
   ]
  },
  {
   "title": "Subgraph Indexing Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "deployment_blocks_behind" }
   ]
  }
 ]
}